// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ7HbtLbglNvtP9k5e2Z-TuWzT22Jss-0',
    appId: '1:109394563647:web:ef5d56ddb1e9b26e21de8a',
    messagingSenderId: '109394563647',
    projectId: 'oilguard',
    authDomain: 'oilguard.firebaseapp.com',
    storageBucket: 'oilguard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx8P4cMPeEw8nqLeLWvm47z6-XUJQydAk',
    appId: '1:109394563647:android:6ebddb38d9c5941921de8a',
    messagingSenderId: '109394563647',
    projectId: 'oilguard',
    storageBucket: 'oilguard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjor0-tkrheCcnu1qFVNeCNgoYryqVdoY',
    appId: '1:109394563647:ios:0714847c0760baa821de8a',
    messagingSenderId: '109394563647',
    projectId: 'oilguard',
    storageBucket: 'oilguard.appspot.com',
    iosBundleId: 'com.example.oilGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjor0-tkrheCcnu1qFVNeCNgoYryqVdoY',
    appId: '1:109394563647:ios:0714847c0760baa821de8a',
    messagingSenderId: '109394563647',
    projectId: 'oilguard',
    storageBucket: 'oilguard.appspot.com',
    iosBundleId: 'com.example.oilGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ7HbtLbglNvtP9k5e2Z-TuWzT22Jss-0',
    appId: '1:109394563647:web:e2c65bffeda0164821de8a',
    messagingSenderId: '109394563647',
    projectId: 'oilguard',
    authDomain: 'oilguard.firebaseapp.com',
    storageBucket: 'oilguard.appspot.com',
  );
}
